name: Gitaction learing 1
on: 
  push:
   paths:
     - "testfloder1"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - name: checkout in dir
        working-directory: testfolder1
        run: python3 hello.py
