name: Gitaction learing 1
on: 
  push:
    paths:
      - testfolder1/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - name: checkout in dir
        working-directory: testfolder1
        run: python3 hello.py
---
name: monorepo-actions-2
on:
  push:
    paths:
      - 'testfolder2/**/*'
jobs:
  build_service_2:
    name: Build Service 2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: check work dir 2
      working-directory: testfolder2
      run: python3 hello.py


