name: Gitaction learing 1
on:
  push:
    paths:
      - testfolder1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - name: checkout in dir
        working-directory: testfolder1
        run: python3 hello.py


  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - name: checkout in dir
        working-directory: testfolder2
        run: python3 hello.py      


